# Generated by Django 2.0.6 on 2018-11-02 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='feedID',
            field=models.CharField(default='0', max_length=100),
        ),
    ]
