# Generated by Django 2.1.3 on 2018-11-07 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0003_auto_20181102_1434'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='thumb',
            field=models.ImageField(blank=True, default='default.png', upload_to=''),
        ),
    ]
