# Generated by Django 2.1.3 on 2018-11-07 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0004_record_thumb'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='thumb',
        ),
    ]
