# Generated by Django 2.1.3 on 2018-11-08 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0007_pet'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='id',
        ),
        migrations.AlterField(
            model_name='record',
            name='feedID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
