# Generated by Django 2.1.3 on 2018-11-21 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0009_auto_20181121_1429'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pet',
            name='author',
        ),
    ]
