# Generated by Django 2.1.3 on 2018-11-22 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0011_pet_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pet',
            name='author',
        ),
        migrations.RemoveField(
            model_name='record',
            name='author',
        ),
        migrations.AddField(
            model_name='record',
            name='author_id',
            field=models.IntegerField(default='1'),
        ),
    ]
