# Generated by Django 2.1.3 on 2018-11-22 10:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0012_auto_20181122_1039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='author_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
