# Generated by Django 2.1.3 on 2018-11-22 11:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('records', '0013_auto_20181122_1047'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='author_id',
        ),
        migrations.AddField(
            model_name='pet',
            name='author',
            field=models.CharField(default='auth.User', max_length=100),
        ),
        migrations.AddField(
            model_name='record',
            name='author',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
