# Generated by Django 2.1.3 on 2018-11-22 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0015_auto_20181122_1106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='additionalInfo',
            field=models.TextField(default=''),
        ),
    ]
