# Generated by Django 2.1.3 on 2018-11-25 23:12

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0018_auto_20181122_1333'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='selectPet',
            field=models.TextField(default=None, verbose_name=django.contrib.auth.models.User),
        ),
    ]
