# Generated by Django 2.1.3 on 2018-11-25 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0019_record_selectpet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='selectPet',
            field=models.TextField(default=''),
        ),
    ]
