# Generated by Django 2.1.3 on 2018-11-26 09:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0021_auto_20181125_2314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='selectPet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='records.Pet'),
        ),
    ]
