# Generated by Django 2.1.3 on 2018-11-26 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0022_auto_20181126_0908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='additionalInfo',
            field=models.TextField(default=' '),
        ),
    ]
